name: Prettier test
on: [push, pull_request]
jobs:
  build:
    name: Prettier run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: format